# Generated by Django 6.0.6 on 2026-07-27 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_add_product_filter_choices'),
        ('accounts', '0032_coinrequest_reject_reason_alter_coinrequest_status'),
    ]

    operations = [
    ]
