# Generated by Django 6.0.6 on 2026-07-27 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_merge_20260727_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinRewardLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(choices=[('first_login', 'First Login'), ('daily_login', 'Daily Login'), ('bonus_10', '10 Days Bonus'), ('bonus_20', '20 Days Bonus'), ('bonus_30', '30 Days Bonus')], max_length=20)),
                ('coins', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_rewards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'login_date')},
            },
        ),
    ]
